<?xml version="1.0" encoding="utf-8"?><Database Name="FBFeeds" Class="ExampleDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.1.1.1;Initial Catalog=FBFeeds;User ID=sa" SettingsObjectName="WebServiceExample.Properties.Settings" SettingsPropertyName="FBFeedsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Accounts" Member="tbl_Accounts">
    <Type Name="tbl_Account">
      <Column Name="AccountID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FBUID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmailVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Salt" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AccessToken" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProfilePicture" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ConfirmationCode" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>